### PR TITLE
Feat/enabled all features

### PR DESCRIPTION
**Pull request by hassaanfarooq01**
Enabled all features of SDK in branch. 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced functionality in Ultralytics Hub SDK with the activation of previously placeholder methods.

### 📊 Key Changes
- Activated methods in hub_client.py that were previously throwing a "Coming Soon" exception, such as `dataset()`, `project()`, `project_list()`, and `dataset_list()`.
- Fixed `get_weights_url` method in models.py to correctly access the `resume` weight URL.

### 🎯 Purpose & Impact
- **Purpose:** To provide actual functionality to methods that are essential for interacting with datasets, projects, and lists within Ultralytics' infrastructure. This allows authenticated users to work effectively with the SDK.
- **Impact:** Users now have access to critical functionality, including retrieving datasets, projects, and lists, which enhances their overall experience and productivity with the Ultralytics platform. The bug fix in the `get_weights_url` method also ensures users can correctly retrieve URLs for model weights, improving reliability.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@hassaanfarooq01 @sergiuwaxmann is this ready to merge? What's the status here? 

I'm extremely uncomfortable merging any changes here as we completely lack GitHub CI, so there's no way for me to know that what you've changed here @hassaanfarooq01 will not break main/develop branches.

**Comment by glenn-jocher** [comment]
@hassaanfarooq01 see https://github.com/ultralytics/hub-sdk/pull/94

**Comment by sergiuwaxmann** [comment]
@glenn-jocher These are changes that @hassaanfarooq01 said we need to merge to fix existing issue raised by @yogendrasinghx. If I am not mistaking, @yogendrasinghx is currently testing these changes.

I agree, we should prioritize adding tests so we can safely merge changes.
@hassaanfarooq01 Please focus on adding tests to HUB SDK and if possible, explain the changes on this branch to @glenn-jocher.

**Comment by glenn-jocher** [comment]
@sergiuwaxmann @hassaanfarooq01 @yogendrasinghx I'm merging this PR solely based on your opinions here that it needs to be merged, I'm blind to see if this will cause any downstream issues but don't want to stand in the way of further development. 

**If we are to keep this repo and not delete it then it absolutely requires tests and CI, the current status is completely unnacceptable.**

**Pull request merged**
