### PR TITLE
Add pre-commit integrations

### PR DESCRIPTION
**Pull request by glenn-jocher**
Adds pre-commit hooks to the hub-sdk repo.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@kalenmike @hassaanfarooq01 I've implemented pre-commit hooks for this repo. They've automatically updated many latent issues and created a list of remaining issues that should be manually resolved in https://results.pre-commit.ci/run/github/671533637/1702916559.KdKu4s5eTsO00kkRlp3wlA

Please review this list and fix these issues.
Screenshot 2023-12-18 at 17 25 30

**Comment by kalenmike** [comment]
@glenn-jocher Can you help out here with the CLA issue? I think this repo is missing some setup.

**Review by kalenmike — APPROVED** [review]

**Comment by kalenmike** [comment]
I have read the CLA Document and I sign the CLA

**Comment by kalenmike** [comment]
@glenn-jocher Can you sign the CLA on this repo?

**Comment by glenn-jocher** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@kalenmike ok I signed the CLA now (didn't realize it was per-repo).

I think we should probably wait so I can get `ultralytics` pyproject.toml PR completed and then port those changes over this PR.

**Comment by glenn-jocher** [comment]
recheck

**Comment by glenn-jocher** [comment]
Maybe the CLA bot requires new tokens for this repo.

**Comment by kalenmike** [comment]
@glenn-jocher Yeah something is up with the CLA. We want to merge this PR so that we can run precommits on the other open PR's

**Comment by kalenmike** [comment]
recheck

**Comment by kalenmike** [comment]
recheck

**Pull request merged**
